### PR TITLE
Stop using JavaPluginConvention for Gradle 7.1+

### LINKED ISSUE #307: Gradle 8.x Deprecates PluginConvention and will be Removed in Gradle 9.0
## What is the smallest, simplest way to reproduce the problem?

This is used in https://github.com/openrewrite/rewrite-gradle-plugin/blob/main/plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java#L103
See 
https://docs.gradle.org/current/userguide/upgrading_version_8.html#deprecated_access_to_conventions

### PR DESCRIPTION
**Pull request by quaff**
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.7/userguide/upgrading_version_8.html#java_convention_deprecation

Fixes #307

### CODE REVIEW

File: plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java [hunk 1]
```diff
@@ -98,10 +100,16 @@ private static void configureProject(Project project, RewriteExtension extension
             }
 
             //Collect Java metadata for each project (used for Java Provenance)
-            //Using the older javaConvention because we need to support older versions of gradle.
-            @SuppressWarnings("deprecation")
-            JavaPluginConvention javaConvention = project.getConvention().getPlugin(JavaPluginConvention.class);
-            javaConvention.getSourceSets().all(sourceSet -> {
+            SourceSetContainer sourceSets;
+            if (project.getGradle().getGradleVersion().compareTo("7.0") > 0) {
```
Comment (shanman190) [inline plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java:104]:
```suggestion
            if (GradleVersion.current().compareTo(GradleVersion.version("7.1")) >= 0) {
```

Specifically, the `GradleVersion` has better semver semantics and there would have been bugs introduced with the previous implementation for 7.0.1 and 7.0.2 as the `JavaPluginExtension#getSourceSets()` method is first introduced in 7.1.

File: plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java [hunk 2]
```diff
@@ -98,10 +100,16 @@ private static void configureProject(Project project, RewriteExtension extension
...
+                sourceSets = project.getExtensions().getByType(JavaPluginExtension.class).getSourceSets();
+            } else {
+                //Using the older javaConvention because we need to support older versions of gradle.
+                @SuppressWarnings("deprecation")
+                JavaPluginConvention javaConvention = project.getConvention().getPlugin(JavaPluginConvention.class);
+                sourceSets = javaConvention.getSourceSets();
```
Comment (shanman190) [inline plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java:110]: This will work for now, but if 9.0 actually removes the conventions or `JavaPluginConvention`, then this code will no longer compile when the Gradle wrapper is upgraded to 9.0 in this repo and will require being refactored again.

Comment (quaff) [reply plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java:110]: > this code will no longer compile when the Gradle wrapper is upgraded to 9.0 in this repo and will require being refactored again.

Yes, but I think released versions will still works fine with 9.0+, and no warning for 7.1+.

**Comment by timtebeek** [comment]
Thanks a lot for this @quaff ! Any concerns before we merge this in @shanman190 ?

**Comment by shanman190** [comment]
For now this is probably fine for now at least.

The one concern that comes to mind is on JVMs that preemptively load all classes and the `JavaPluginConvention` actually being removed. In that case, we would most definitely begin to receive reports of the plugin failing to load the old class. These JVMs seem to be fairly uncommon though.
